### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by miflck** [carwyn/veillance#4]
after several days running with let the machine sleep between etc, it crashed. last lines: 

`{"Id":9370,"Name":"10.0.1.19","Type":"DNS","Text":"ocsp.apple.com"}
Processed 800000 packets (698914339 bytes) in 102h17m52.790857977s (errors: 44, type:2)
{"Id":9371,"Name":"10.0.1.19","Type":"DNS","Text":"configuration.apple.com.edgekey.net"}
{"Id":9372,"Name":"10.0.1.19","Type":"DNS","Text":"p32-ckdevice.icloud.com"}
Processed 801000 packets (699752957 bytes) in 102h17m54.718576344s (errors: 44, type:2)
{"Id":9373,"Name":"10.0.1.19","Type":"DNS","Text":"p32-caldav-current.edge.icloud.apple-dns.net"}
{"Id":9374,"Name":"10.0.1.19","Type":"DNS","Text":"gsp10-ssl.ls-apple.com.akadns.net"}
Processed 802000 packets (700592611 bytes) in 102h17m57.722233964s (errors: 44, type:2)
{"Id":9375,"Name":"10.0.1.19","Type":"DNS","Text":"e.crashlytics.com"}
{"Id":9376,"Name":"10.0.1.19","Type":"DNS","Text":"e6858.dsce9.akamaiedge.net"}
Processed 803000 packets (701393376 bytes) in 102h18m0.726005482s (errors: 44, type:2)
{"Id":9377,"Name":"10.0.1.19","Type":"DNS","Text":"help.apple.com"}
Processed 804000 packets (702233715 bytes) in 102h18m3.729838274s (errors: 44, type:2)
Processed 805000 packets (703042786 bytes) in 102h18m6.735103657s (errors: 44, type:2)
Processed 806000 packets (703854494 bytes) in 102h18m10.737732629s (errors: 44, type:2)
fatal error: HTTP/17.132.5.59->10.0.1.19 80->54767: failed to get body(parsed len:1911140): unexpected EOF
concurrent map read and map writeHTTP/17.132.5.59->10.0.1.19 80->54780: failed to get body(parsed len:1292100): unexpected EOF

goroutine 13431 [running]:
runtime.throw(0x43b09a9, 0x21)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc42431a898 sp=0xc42431a878
runtime.mapaccess2_faststr(0x4325c40, 0xc4211d53e0, 0x43a8729, 0x12, 0xc42755f701, 0xc426013810)
	/usr/local/go/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc42431a8f8 sp=0xc42431a898
main.Error(0x43a8729, 0x12, 0x43b5607, 0x2f, 0xc42431ada8, 0x3, 0x3)
	/Users/fgm4/gocode/src/github.com/carwyn/veillance/interceptor/main.go:113 +0x62 fp=0xc42431a960 sp=0xc42431a8f8
main.(*httpReader).run(0xc42664bc00, 0xc4211dcaa0)
	/Users/fgm4/gocode/src/github.com/carwyn/veillance/interceptor/main.go:172 +0x1c76 fp=0xc42431afa0 sp=0xc42431a960
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42431afa8 sp=0xc42431afa0
created by main.(*tcpStreamFactory).New
	/Users/fgm4/gocode/src/github.com/carwyn/veillance/interceptor/main.go:295 +0xbfa`

**Comment by miflck** [comment]
it doesnt let me post the whole output because of its too long...
i dont know if this happend all at the same time because of i let it running and didn't checked for a day. i just saw it now.

**Comment by carwyn** [comment]
Can you attach the output? (drag the file into the comment box)

**Comment by miflck** [comment]
oh, did not know that. i have it attached in slack. i am not on my machine anymore, but can post it on github in 1.5h. 

Von meinem iPhone gesendet

**Comment by carwyn** [comment]
Panic Dump:
[interceptor-panic.txt](https://github.com/carwyn/veillance/files/708127/interceptor-panic.txt)

**Comment by miflck** [comment]
it happend again...


{"Id":12191,"Name":"10.0.1.6","Type":"DNS","Text":"i.ytimg.com"}
client.go:70: Send: &{12191 {10.0.1.6 DNS} i.ytimg.com}
{"Id":12192,"Name":"10.0.1.6","Type":"DNS","Text":"de.ioam.de"}
client.go:70: Send: &{12192 {10.0.1.6 DNS} de.ioam.de}
{"Id":12193,"Name":"10.0.1.6","Type":"DNS","Text":"gs-loc.apple.com"}
client.go:70: Send: &{12193 {10.0.1.6 DNS} gs-loc.apple.com}
{"Id":12194,"Name":"10.0.1.6","Type":"DNS","Text":"http.00.s.sophosxl.net"}
client.go:70: Send: &{12194 {10.0.1.6 DNS} http.00.s.sophosxl.net}
{"Id":12195,"Name":"10.0.1.6","Type":"DNS","Text":"www.sueddeutsche.de"}
client.go:70: Send: &{12195 {10.0.1.6 DNS} www.sueddeutsche.de}
Failed to gzip decode: gzip: invalid header{"Id":12196,"Name":"10.0.1.6","Type":"DNS","Text":"polpix.sueddeutsche.com"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x280 pc=0x4085817]

goroutine 22228 [running]:
panic(0x4327900, 0xc4200140b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
compress/gzip.(*Reader).Read(0x0, 0xc42dbc5000, 0x1000, 0x1000, 0xc42237bad0, 0xd0, 0xd0)
	/usr/local/go/src/compress/gzip/gunzip.go:242 +0x37
golang.org/x/net/html.readAtLeastOneByte(0x4577a20, 0x0, 0xc42dbc5000, 0x1000, 0x1000, 0xc4200b2400, 0x68, 0x43d074f)
	/Users/fgm4/gocode/src/golang.org/x/net/html/token.go:299 +0x60
golang.org/x/net/html.(*Tokenizer).readByte(0xc42237bad0, 0x70)
	/Users/fgm4/gocode/src/golang.org/x/net/html/token.go:273 +0x265
golang.org/x/net/html.(*Tokenizer).Next(0xc42237bad0, 0xc4249097a0)
	/Users/fgm4/gocode/src/golang.org/x/net/html/token.go:980 +0x99
golang.org/x/net/html.(*parser).parse(0xc4293b69a0, 0xc4249097a0, 0xc42237bad0)
	/Users/fgm4/gocode/src/golang.org/x/net/html/parse.go:2001 +0xa9
golang.org/x/net/html.Parse(0x4577a20, 0x0, 0x43ac7a4, 0x19, 0xc422467d08)
	/Users/fgm4/gocode/src/golang.org/x/net/html/parse.go:2026 +0x10c
main.(*httpReader).run(0xc4244fcd00, 0xc4211ecaa0)
	/Users/fgm4/gocode/src/github.com/carwyn/veillance/interceptor/main.go:209 +0xad0
created by main.(*tcpStreamFactory).New
	/Users/fgm4/gocode/src/github.com/carwyn/veillance/interceptor/main.go:295 +0xbfa
fell11-fgm4:interceptor fgm4$

**Comment by miflck** [comment]
seems like it dont like 
http://www.sueddeutsche.de

**Comment by carwyn** [comment]
sueddeutsche.de:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x280 pc=0x4085817]

goroutine 203 [running]:
panic(0x4327900, 0xc4200140b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
compress/gzip.(*Reader).Read(0x0, 0xc422637000, 0x1000, 0x1000, 0xc421212410, 0xd0, 0xd0)
	/usr/local/go/src/compress/gzip/gunzip.go:242 +0x37
golang.org/x/net/html.readAtLeastOneByte(0x4577a20, 0x0, 0xc422637000, 0x1000, 0x1000, 0x0, 0x68, 0x43d074f)
	/Users/fgm4/gocode/src/golang.org/x/net/html/token.go:299 +0x60
golang.org/x/net/html.(*Tokenizer).readByte(0xc421212410, 0x70)
	/Users/fgm4/gocode/src/golang.org/x/net/html/token.go:273 +0x265
golang.org/x/net/html.(*Tokenizer).Next(0xc421212410, 0xc4222e0000)
	/Users/fgm4/gocode/src/golang.org/x/net/html/token.go:980 +0x99
golang.org/x/net/html.(*parser).parse(0xc4200fa160, 0xc4222e0000, 0xc421212410)
	/Users/fgm4/gocode/src/golang.org/x/net/html/parse.go:2001 +0xa9
golang.org/x/net/html.Parse(0x4577a20, 0x0, 0x43ac7a4, 0x19, 0xc421661d08)
	/Users/fgm4/gocode/src/golang.org/x/net/html/parse.go:2026 +0x10c
main.(*httpReader).run(0xc4214f3180, 0xc4211e4a60)
	/Users/fgm4/gocode/src/github.com/carwyn/veillance/interceptor/main.go:209 +0xad0
created by main.(*tcpStreamFactory).New
	/Users/fgm4/gocode/src/github.com/carwyn/veillance/interceptor/main.go:295 +0xbfa
```
